### ISSUE TITLE
[JOSS Review]: Issue loading Water Compressibility

### ISSUE THREAD

**Issue by AnantHariharan1996** [frank1010111/bluebonnet#18]
I have been testing the fluids tool as documented in: https://bluebonnet.readthedocs.io/en/latest/fluids.html

I ran into an issue when trying to calculate water compressibility as in the following line:

from bluebonnet.fluids.water import compressibility_water_McCain

Which results in the following issue:

---->  from bluebonnet.fluids.water import compressibility_water_McCain

ImportError: cannot import name 'compressibility_water_McCain' from 'bluebonnet.fluids.water' (/Users/ananthariharan/opt/anaconda3/lib/python3.9/site-packages/bluebonnet/fluids/water.py). 

Upon inspection of the version of water.py that I have downloaded, it looks like compressibility_water_McCain is not a module there, thought it appears to be in the most recent version on the repo in the src folder. Let me know if there's something different I should be doing or if I should be using a different version: 

I installed the code using pip install bluebonnet.

This is part of the reviewing process for JOSS: https://github.com/openjournals/joss-reviews/issues/5255

**Comment by frank1010111** [comment]
I've released version 0.2.0 to PyPI, which should resolve this issue.

**Comment by AnantHariharan1996** [comment]
Thanks! I'm able to work with that module now.
