### ISSUE TITLE
[JOSS Review] KeyError when Well 20 data is missing

### ISSUE THREAD

**Issue by RyanSwindeman** [frank1010111/bluebonnet#19]
In the docs, specifically at [https://bluebonnet.readthedocs.io/en/latest/forecast_varying.html#fit-wells](https://bluebonnet.readthedocs.io/en/latest/forecast_varying.html#fit-wells), we use data from Well 20 that isn't directly included in the repo. Can you provide a note on using git lfs (or any other tool) to fetch that data? If left as is, we obtain the following error when running the example verbatim:
```
KeyError: "None of [Index(['Days', 'Gas', 'Pressure'], dtype='object')] are in the [columns]"
```

This is part of the reviewing process for JOSS: openjournals/joss-reviews#5255

**Comment by frank1010111** [comment]
Thank you for your comment. The data from Well 20 is available only after you install git-lfs. See [the contributing part of the documentation](https://bluebonnet.readthedocs.io/en/latest/contributing.html#get-started).

I chose to use git-lfs for this with the expectation that several large files might be added to the repository for illustrative purposes.

Hope this helps.

**Comment by RyanSwindeman** [comment]
Woops. Confirmed. I have it working, but I should be more precise in wording. Can you please include a blurb in the readme (maybe just after the python env/packages) or in the documents (where this error would otherwise appear) explicitly stating `git lfs install`/`git lfs pull` needs to be run to grab large files? Right now, the only mention of git lfs I see is under `Contributing` in local development. This means users who grabbed the package from pip will see this error if running through the documentation in order.

**Comment by frank1010111** [comment]
I decided the simplest solution was to move that particular file from git-lfs to git tracking. You can see the changes at #24.
