### ISSUE TITLE
[JOSS Review] Documentation tweaks

### ISSUE THREAD

**Issue by RyanSwindeman** [frank1010111/bluebonnet#20]
Great job overall. Please consider the following slight adjustments:
- I’d add a note at the beginning saying these code snippets are meant to be run in a jupyter notebook. It'd be extra nice to include a jupyter notebook that demonstrates the same code in the documentation. It probably already exists since Magics are used there.
- Often there are trailing `;` that can be removed in the examples (often after `ax.set(...)`)
- In [Simulating Tight Oil Flow](https://bluebonnet.readthedocs.io/en/latest/oil_flow.html#single-phase-oil-simulation) the `( );`  encapsulating the `pvt_oil.plot` is unnecessary and can be removed
- In [Varying Fracface Pressure](https://bluebonnet.readthedocs.io/en/latest/forecast_varying.html#) I’m unclear of the meaning of `[Text(0.5, 0, 'Time'), None, Text(0, 0.5, 'Pressure')]` and suspect it should be removed

This is part of the reviewing process for JOSS: openjournals/joss-reviews#5255

**Comment by frank1010111** [comment]
Thank you for your suggestions. 

Yes, code snippets portion of the documentation is generated from [jupyter notebooks found here](https://github.com/frank1010111/bluebonnet/tree/main/docs).

I added the trailing semicolons to suppress extra outputs in the source jupyter notebooks.

I will remove the encapsulating parentheses in Simulating Tight Oil Flow and extra jupyter printout of `[Text(0.5, 0, 'Time'), None, Text(0, 0.5, 'Pressure')]` in Varying Fracface Pressure.
