### ISSUE TITLE
[JOSS Review] Environment details

### ISSUE THREAD

**Issue by RyanSwindeman** [frank1010111/bluebonnet#21]
2 questions associated with the Python environment:
- When installing bluebonnet, what versions of Python are supported? I see a closed PR for 3.11, but what's the lower bound? Can you include this answer in the documentation?
- Could you explicitly include pip dependencies somewhere (e.g. in a `requirements.txt` file)? I know they're listed in the paper acknowledgments.

This is part of the reviewing process for JOSS: https://github.com/openjournals/joss-reviews/issues/5255

**Comment by frank1010111** [comment]
Thank you for your suggestions.

I will add python versions to the documentation in #22. For package dependencies, I'm reticent to include a `requirements.txt` for fear that it will drift out of agreement with the requirements specified in `pyproject.toml`

**Comment by frank1010111** [comment]
Addressed in the above merged pull request.
