### ISSUE TITLE
[JOSS REVIEW] NotImplementedError Remarks

### ISSUE THREAD

**Issue by RyanSwindeman** [frank1010111/bluebonnet#23]
@frank1010111 could you please comment on the `NotImplementedError`s we see in `flow/reservoir.py`'s `MultiPhaseReservoir`? Thanks for any information.

This is part of the reviewing process for JOSS: https://github.com/openjournals/joss-reviews/issues/5255

**Comment by frank1010111** [comment]
Yes, this is planned future functionality in #3 that would be nice to have, but its effect on tight-oil production matching and forecasting has not yet been studied.

**Comment by RyanSwindeman** [comment]
Understood. Thanks for the explanation. Looking forward to that one day in the future
